DataTorrent/Malhar

- contrib/pom.xml
- contrib/src/main/java/com/datatorrent/contrib/solr/AbstractSolrInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/solr/AbstractSolrOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/solr/CloudSolrServerConnector.java
- contrib/src/main/java/com/datatorrent/contrib/solr/ConcurrentUpdateSolrServerConnector.java
- contrib/src/main/java/com/datatorrent/contrib/solr/HttpSolrServerConnector.java
- contrib/src/main/java/com/datatorrent/contrib/solr/LBHttpSolrServerConnector.java
- contrib/src/main/java/com/datatorrent/contrib/solr/README.md
- contrib/src/main/java/com/datatorrent/contrib/solr/SolrInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/solr/SolrOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/solr/SolrServerConnector.java
- contrib/src/test/java/com/datatorrent/contrib/solr/SolrInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/solr/SolrOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/solr/SolrOutputOperatorTest.java
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/elevate.xml
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/lang/stopwords_en.txt
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/protwords.txt
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/schema.xml
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/solrconfig.xml
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/stopwords.txt
- contrib/src/test/resources/com/datatorrent/contrib/solr/collection1/conf/synonyms.txt
- contrib/src/test/resources/com/datatorrent/contrib/solr/docs/books.csv
- contrib/src/test/resources/com/datatorrent/contrib/solr/docs/solr.xml
Adding Solr Operators:
1. Input Operator: Reads data from Solr server based on user defined queries.
2. Output Operator: Writes data to Solr server.
3. Unit tests which uses embedded Solr Server.
4. resources file which needs to initialize embedded solr server for unit testing.
> Mlhr 1496 solr operators

- demos/dimensions/src/main/resources/META-INF/properties.xml
This is to conditionally show the app data link in the console.
> add APPLICATION_DATA_LINK to dimensions demo package

- contrib/src/main/java/com/datatorrent/contrib/hbase/HBaseStore.java
Added ability to specify user name in principal and keytab that would be dynamically substituted with unix user the application is running as at runtime. Added automatic relogin to handle token expiry.
> Squashed commit of the following:

- contrib/pom.xml
- contrib/src/main/java/com/datatorrent/contrib/kinesis/AbstractKinesisInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/AbstractKinesisOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/KinesisConsumer.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/KinesisStringInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/KinesisStringOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/KinesisUtil.java
- contrib/src/main/java/com/datatorrent/contrib/kinesis/ShardManager.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisOperatorTestBase.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisOutputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisPartitionableInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisTestConsumer.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/KinesisTestProducer.java
- contrib/src/test/java/com/datatorrent/contrib/kinesis/ShardManagerTest.java
- demos/twitter/pom.xml
- demos/twitter/src/main/java/com/datatorrent/demos/twitter/KinesisHashtagsApplication.java
- demos/twitter/src/main/resources/META-INF/properties.xml
> Implemented Kinesis Input and Ouput Operators

- library/src/main/java/com/datatorrent/lib/script/JavaScriptOperator.java
> Added default constructor in MyBindings in JavaScriptOperator.

- demos/twitter/src/main/resources/META-INF/properties-Twitter-KinesisDemo.xml
- demos/twitter/src/main/resources/META-INF/properties.xml
Tested and works with the latest gateway changes that resolve SPOI-3927.
@chaithu14 i hate to step in and open a competing pull request, but this was something I needed to have working in order to update the UI.
> SPOI-3926: Created new config file for kinesis demo app with added required properties

- benchmark/src/test/java/com/datatorrent/benchmark/CouchBaseBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/kafka/KafkaInputBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/kafka/KafkaOutputBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/memsql/MemsqlOutputBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/EventClassifierAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/EventClassifierNumberToHashDoubleAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/EventGeneratorAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/EventIncrementerAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/FilterClassifierAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/FilteredEventClassifierAppTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/testbench/ThroughputCounterAppTest.java
commit 4fe67d3f88c397e5787de075d3a7b3a2d4afce29
Merge: 8da8db1 08ad701
Author: Prerna Manaktala <prerna@datatorrent.com>
Date:   Fri Feb 6 17:48:04 2015 -0800
Merge branch 'dt-dev' into MLHR-1663
commit 8da8db1bae68951c1878f8c3cd356319cb88986a
Author: Prerna Manaktala <prerna@datatorrent.com>
Date:   Fri Feb 6 17:45:10 2015 -0800
Changed exception handling mechanism.
commit cc8c07acee808b021df74772053411cb5f3d4d73
Author: Prerna Manaktala <prerna@datatorrent.com>
Date:   Fri Feb 6 16:12:00 2015 -0800
Changed back the names of few benchmark apps.
commit 4e633c1a0fb1f07054d8b09a4a98d44f480010c9
Merge: 790eca2 f15dd24
Author: Prerna Manaktala <prerna@datatorrent.com>
Date:   Fri Feb 6 16:02:25 2015 -0800
merge
commit 790eca29f51330c1de10c9a89c98c516beb57338
Author: Prerna Manaktala …
> Squashed commit for mlhr-1663

- library/src/main/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperator.java
- library/src/test/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperatorTest.java
A feature to rotate files periodically. The rotation period is specified as a parameter.
> Feature to rotate files periodically after a specified number of windows have elapsed

- benchmark/pom.xml
Excluded hadoop jars already provided by platform in benchmark.This resolves the jira MLHR-1673.
> #MLHR-1673

- library/src/main/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperator.java
Fixed recording total time spent writing bytes.
> Mlhr 1679 pull

- benchmark/pom.xml
- benchmark/src/main/java/com/datatorrent/benchmark/hive/HiveInsertBenchmarkingApp.java
- benchmark/src/main/java/com/datatorrent/benchmark/hive/HiveMapInsertBenchmarkingApp.java
- benchmark/src/main/resources/META-INF/properties.xml
- benchmark/src/site/conf/dt-site-hive.xml
- benchmark/src/test/java/com/datatorrent/benchmark/hive/HiveInsertBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/hive/HiveMapBenchmarkTest.java
- contrib/pom.xml
- contrib/src/main/java/com/datatorrent/contrib/hive/AbstractFSRollingOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hive/HiveOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hive/HiveStore.java
- contrib/src/main/java/com/datatorrent/contrib/hive/HiveStreamCodec.java
- contrib/src/test/java/com/datatorrent/contrib/hive/FSRollingMapTestImpl.java
- contrib/src/test/java/com/datatorrent/contrib/hive/FSRollingTestImpl.java
- contrib/src/test/java/com/datatorrent/contrib/hive/HiveMockTest.java
- contrib/src/test/java/com/datatorrent/contrib/hive/HiveStoreTest.java
- library/src/main/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperator.java
Hive-HDFS Operator which resolves mlhr-1544.
> #MLHR-1544

- demos/echoserver/pom.xml
- demos/echoserver/src/assemble/appPackage.xml
- demos/echoserver/src/main/java/com/datatorrent/demos/echoserver/Application.java
- demos/echoserver/src/main/java/com/datatorrent/demos/echoserver/Message.java
- demos/echoserver/src/main/java/com/datatorrent/demos/echoserver/MessageReceiver.java
- demos/echoserver/src/main/java/com/datatorrent/demos/echoserver/MessageResponder.java
- demos/echoserver/src/main/java/com/datatorrent/demos/echoserver/NetworkManager.java
- demos/echoserver/src/main/resources/META-INF/properties.xml
- demos/echoserver/src/site/conf/my-app-conf1.xml
- demos/echoserver/src/test/java/com/datatorrent/demos/echoserver/ApplicationTest.java
- demos/echoserver/src/test/resources/log4j.properties
- demos/pom.xml
.The application uses two operators for receiving messages and responding to them
> Echo server demo that receives messages from a socket and echos them back to the client

- benchmark/pom.xml
- benchmark/src/main/java/com/datatorrent/benchmark/stream/DevNullCounterBenchmark.java
- benchmark/src/main/java/com/datatorrent/benchmark/stream/StreamDuplicaterApp.java
- benchmark/src/main/java/com/datatorrent/benchmark/stream/StreamMergeApp.java
- benchmark/src/main/java/com/datatorrent/benchmark/testbench/RandomEventGeneratorApp.java
- benchmark/src/main/java/com/datatorrent/benchmark/testbench/SeedEventGeneratorApp.java
- contrib/pom.xml
Removed not needed dependencies from benchmark/pom.xml and contrib/pom.xml
> MLHR-1680_Review

- benchmark/pom.xml
Added slf4j-api exclusion in cassandra.
> Removed exclusions clutter from benchmark/pom.xml

- contrib/src/main/java/com/datatorrent/contrib/kafka/AbstractKafkaInputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/kafka/KafkaInputOperatorTest.java
> Added the idempotent flag to the kafka Input Operator

- benchmark/src/main/java/com/datatorrent/benchmark/kafka/BenchmarkKafkaInputOperator.java
- benchmark/src/main/java/com/datatorrent/benchmark/kafka/KafkaInputBenchmark.java
- benchmark/src/site/conf/dt-site-kafka.xml
- contrib/src/main/java/com/datatorrent/contrib/kafka/AbstractKafkaInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kafka/SimpleKafkaConsumer.java
- contrib/src/test/java/com/datatorrent/contrib/kafka/KafkaInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/kafka/KafkaPartitionableInputOperatorTest.java
Change the zookeeper set configuration. Added a unit test for parsing. Fixed the compilation errors in benchmark.
> MLHR-1693: Change the zookeeper set configuration.

- library/src/main/java/com/datatorrent/lib/io/fs/FileSplitter.java
- library/src/test/java/com/datatorrent/lib/io/fs/FileSplitterTest.java
- Asynchronous scanner
- Discovery based on file modification time
- Block threshold
> File splitter improvements

- library/src/main/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperator.java
- library/src/main/java/com/datatorrent/lib/io/fs/FilterStreamCodec.java
- library/src/main/java/com/datatorrent/lib/io/fs/FilterStreamCodecContext.java
- library/src/main/java/com/datatorrent/lib/io/fs/FilterStreamContext.java
- library/src/main/java/com/datatorrent/lib/io/fs/FilterStreamProvider.java
- library/src/test/java/com/datatorrent/lib/io/fs/AbstractFileOutputOperatorTest.java
.Compression support via filters and ability to chain multiple filters.
> Filter support for file output including gzip support and filter chaining

- library/src/main/java/com/datatorrent/lib/bucket/AbstractBucket.java
- library/src/main/java/com/datatorrent/lib/bucket/AbstractBucketManager.java
- library/src/main/java/com/datatorrent/lib/bucket/AbstractTimeBasedBucketManager.java
- library/src/main/java/com/datatorrent/lib/bucket/Bucket.java
- library/src/main/java/com/datatorrent/lib/bucket/BucketManager.java
- library/src/main/java/com/datatorrent/lib/bucket/BucketManagerImpl.java
- library/src/main/java/com/datatorrent/lib/bucket/BucketStore.java
- library/src/main/java/com/datatorrent/lib/bucket/ExpirableHdfsBucketStore.java
- library/src/main/java/com/datatorrent/lib/bucket/HdfsBucketStore.java
- library/src/main/java/com/datatorrent/lib/bucket/NonOperationalBucketStore.java
- library/src/main/java/com/datatorrent/lib/bucket/TimeBasedBucketManagerImpl.java
- library/src/main/java/com/datatorrent/lib/dedup/AbstractDeduper.java
- library/src/main/java/com/datatorrent/lib/dedup/DeduperWithHdfsStore.java
- library/src/test/java/com/datatorrent/lib/bucket/BucketManagerTest.java
- library/src/test/java/com/datatorrent/lib/bucket/TimeBasedBucketManagerTest.java
- library/src/test/java/com/datatorrent/lib/dedup/BucketPOJOImpl.java
- library/src/test/java/com/datatorrent/lib/dedup/DeduperSimpleEventTest.java
- library/src/test/java/com/datatorrent/lib/dedup/DeduperSimpleTest.java
- library/src/test/java/com/datatorrent/lib/dedup/DeduperTest.java
- library/src/test/java/com/datatorrent/lib/dedup/SimpleEvent.java
- library/src/test/java/com/datatorrent/lib/dedup/TimeBasedBucketManagerPOJOImpl.java
Abstraction of Deduper to support generic tuples.
> Deduper abstraction

- library/src/main/java/com/datatorrent/lib/io/jms/AbstractJMSInputOperator.java
- library/src/main/java/com/datatorrent/lib/io/jms/JMSObjectInputOperator.java
- library/src/main/java/com/datatorrent/lib/io/jms/JMSStringInputOperator.java
- library/src/test/java/com/datatorrent/lib/io/jms/JMSObjectInputOperatorTest.java
Added multiple ports for jms input operator.
> #MLHR-1702

- library/src/main/java/com/datatorrent/lib/io/jms/JMSMultiPortOutputOperator.java
- library/src/main/java/com/datatorrent/lib/util/ActiveMQMessageListener.java
- library/src/main/java/com/datatorrent/lib/util/ActiveMQMultiTypeMessageListener.java
- library/src/test/java/com/datatorrent/lib/io/jms/JMSMultiPortOutputOperatorTest.java
- library/src/test/java/com/datatorrent/lib/io/jms/JMSOutputOperatorTest.java
- library/src/test/java/com/datatorrent/lib/io/jms/JMSTransactionableStoreTestBase.java
Created an implementation of JMSOutputOperator for Map,ByteArray,Object and String messages to be processed on different ports.
> #MLHR-1703

- contrib/src/main/java/com/datatorrent/contrib/kafka/KafkaSinglePortByteArrayInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/kafka/KafkaSinglePortStringInputOperator.java
- library/src/main/java/com/datatorrent/lib/converter/ByteArrayToStringConverterOperator.java
Deprecated KafkaSinglePortStringInputOperator.java, Added a ByteArrayToString converter in library.
> ByteArrayToStringConverter

- library/src/main/java/com/datatorrent/lib/stream/ArrayListAggregator.java
> Erroneous displayName for ArrayListAggregator

- library/src/main/java/com/datatorrent/lib/bucket/BucketPOJOImpl.java
- library/src/main/java/com/datatorrent/lib/bucket/POJOBucketManager.java
- library/src/main/java/com/datatorrent/lib/bucket/TimeBasedBucketManagerPOJOImpl.java
- library/src/main/java/com/datatorrent/lib/dedup/AbstractDeduper.java
- library/src/main/java/com/datatorrent/lib/dedup/DeduperPOJOImpl.java
- library/src/test/java/com/datatorrent/lib/dedup/BucketSimpleEventImpl.java
- library/src/test/java/com/datatorrent/lib/dedup/DeduperPOJOTest.java
- library/src/test/java/com/datatorrent/lib/dedup/TimeBasedBucketManagerSimpleEventImpl.java
Created an implementation of Deduper,BucketManager and Bucket which can handle any POJO using POJOUtils.Also added a unit test for same.
> DeduperPOJOImplementation

- contrib/src/main/java/com/datatorrent/contrib/cassandra/AbstractCassandraTransactionableOutputOperatorPS.java
- contrib/src/main/java/com/datatorrent/contrib/cassandra/CassandraOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/cassandra/CassandraStore.java
- contrib/src/test/java/com/datatorrent/contrib/cassandra/CassandraOperatorTest.java
Created a POJO implementation for Cassandra Output Operator,added a unit test also.
> CassandraPOJOImplementation

- contrib/src/main/java/com/datatorrent/contrib/couchbase/CouchbasePOJOOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/CouchBaseOutputOperatorTest.java
Created an implementation of CouchbaseOutputOperator which takes in a POJO and writes key value pait to Couchbase.
> POJO implementation of CouchbaseOutputOperator

- library/src/main/java/com/datatorrent/lib/db/jdbc/JdbcPOJOOutputOperator.java
- library/src/test/java/com/datatorrent/lib/db/jdbc/JdbcOperatorTest.java
Implementation of Jdbc Output Operator which takes in a POJO and extracts fields from it and writes them to specific columns in the table specified by user.
> Jdbc POJO Output Operator

- contrib/src/main/java/com/datatorrent/contrib/hive/FSPojoToHiveOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hive/HiveOperator.java
- contrib/src/test/java/com/datatorrent/contrib/hive/HiveMockTest.java
An Implementation of AbstractFSRollingOutputOperator which takes any POJO as input, serializes the POJO as Hive delimiter separated values which are written in text files to hdfs.
> FsToHive Operator POJO Implementation

- contrib/src/main/java/com/datatorrent/contrib/couchdb/AbstractCouchDBOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/CouchDbPOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/MapBasedCouchDbOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/couchdb/CouchDBOutputOperatorTest.java
Map conversion of Tuple is not needed to store a pojo in couchdb, it stores the pojo as it is.
> Improvement to existing couch db pojo implementation

- contrib/src/main/java/com/datatorrent/contrib/couchbase/AbstractCouchBaseOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchbase/AbstractCouchBaseSetOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchbase/CouchbasePOJOSetOperator.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/CouchBaseOutputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/CouchBaseSetTest.java
Added mock test for CouchBaseOutputOperator and made changes to creation of getter in CouchbasePOJOSetOperator.
> #MLHR-1736 CouchBase Mock Test Addition

- apps/logstream/pom.xml
- apps/pom.xml
- benchmark/pom.xml
- contrib/pom.xml
- demos/dimensions/pom.xml
- demos/distributedistinct/pom.xml
- demos/frauddetect/pom.xml
- demos/machinedata/pom.xml
- demos/mobile/pom.xml
- demos/mrmonitor/pom.xml
- demos/mroperator/pom.xml
- demos/pi/pom.xml
- demos/pom.xml
- demos/samplestream/pom.xml
- demos/scalability/pom.xml
- demos/twitter/pom.xml
- demos/uniquecount/pom.xml
- demos/visualdata/pom.xml
- demos/wordcount/pom.xml
- demos/yahoofinance/pom.xml
- library/pom.xml
- pom.xml
- samples/pom.xml
> Updating version to 2.0.3-SNAPSHOT

- library/src/main/java/com/datatorrent/lib/util/PojoUtils.java
Introduced public constructGetter and constructSetter methods that accept Java class including primitive classes as an argument and returned Object implements corresponding GetterX/SetterX interface.
> MLHR-1742 #resolve

- contrib/src/main/java/com/datatorrent/contrib/mongodb/MongoDBOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/mongodb/MongoDBPOJOOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/mongodb/MongoDBOutputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/mongodb/TestPOJO.java
Created an implementation of MongoDBOutputOperator that saves POJO fields in the mongodb database
> MLHR-1737 #resolve

- contrib/src/main/java/com/datatorrent/contrib/memsql/MemsqlPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/memsql/MemsqlPOJOOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/memsql/AbstractMemsqlInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/memsql/AbstractMemsqlOutputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/memsql/MemsqlInputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/memsql/TestInputPojo.java
- library/src/main/java/com/datatorrent/lib/db/jdbc/AbstractJdbcInputOperator.java
Created concrete implementation for MemsqlInputOperator which sets field values from memsql table into an user defined pojo.
> MLHR-1739 #resolve 

- pom.xml
changed scope of dt-common dependency to provided in malhar-all pom.xml
added maven 3.0.0 to prerequisites
> MLHR-1756 #resolve

- library/src/main/java/com/datatorrent/lib/util/PojoUtils.java
- library/src/test/java/com/datatorrent/lib/util/PojoUtilsTest.java
PojoUtils create/constructSetter does not handle boxing/unboxing.
> MLHR-1752 #resolve

- benchmark/src/test/java/com/datatorrent/benchmark/memsql/MemsqlOutputBenchmark.java
- library/src/main/java/com/datatorrent/lib/algo/BottomNMap.java
- library/src/main/java/com/datatorrent/lib/algo/BottomNUniqueMap.java
- library/src/main/java/com/datatorrent/lib/algo/FirstN.java
- library/src/main/java/com/datatorrent/lib/algo/InsertSortDesc.java
- library/src/main/java/com/datatorrent/lib/algo/TopN.java
- library/src/main/java/com/datatorrent/lib/algo/TopNUnique.java
- library/src/main/java/com/datatorrent/lib/io/SimpleSinglePortInputOperator.java
- library/src/main/java/com/datatorrent/lib/testbench/CompareFilterTuples.java
- library/src/main/java/com/datatorrent/lib/testbench/EventClassifierNumberToHashDouble.java
- library/src/main/java/com/datatorrent/lib/testbench/EventGenerator.java
- library/src/main/java/com/datatorrent/lib/testbench/EventIncrementer.java
- library/src/main/java/com/datatorrent/lib/testbench/HttpStatusFilter.java
- library/src/main/java/com/datatorrent/lib/testbench/RandomEventGenerator.java
- library/src/main/java/com/datatorrent/lib/testbench/SeedEventGenerator.java
- library/src/main/java/com/datatorrent/lib/testbench/TopOccurrence.java
- library/src/main/java/com/datatorrent/lib/util/AbstractDimensionTimeBucketOperator.java
- library/src/main/java/com/datatorrent/lib/util/AlertEscalationOperator.java
- library/src/main/java/com/datatorrent/lib/util/AlertThreeLevelTimedEscalationOperator.java
- library/src/main/java/com/datatorrent/lib/util/BaseKeyValueOperator.java
- library/src/main/java/com/datatorrent/lib/util/BaseMatchOperator.java
- library/src/main/java/com/datatorrent/lib/util/JavaScriptFilterOperator.java
Few other small changes like fixing spelling mistakes.
> Improving description of Properties of Operators 

- contrib/src/main/java/com/datatorrent/contrib/couchdb/AbstractCouchDBInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/CouchDbPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/CouchDbPOJOOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/couchdb/CouchDBOutputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/couchdb/CouchDBPOJOInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/couchdb/CouchDBTestHelper.java
- contrib/src/test/java/com/datatorrent/contrib/couchdb/TestInputPOJO.java
A generic implementation of AbstractCouchDBInputOperator that fetches ViewResult rows from CouchDb and emits them as POJOs.
> MLHR-1746 #resolve CouchDb POJO Input Operator

- contrib/src/main/java/com/datatorrent/contrib/couchbase/CouchBasePOJOInputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/CouchBaseInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/CouchbasePOJOTest.java
- contrib/src/test/java/com/datatorrent/contrib/couchbase/TestComplexPojoInput.java
Created an implementation of CouchbaseInputOperator that fetches rows of data from Couchbase store and emits them as POJOs.
> MLHR-1741#resolve

- library/src/main/java/com/datatorrent/lib/io/PubSubWebSocketAppDataQuery.java
- library/src/main/java/com/datatorrent/lib/io/PubSubWebSocketAppDataResult.java
Fixed category for app data query and result operators
> #resolve MLHR-1780

- contrib/src/main/java/com/datatorrent/contrib/hbase/HBaseFieldInfo.java
- contrib/src/main/java/com/datatorrent/contrib/hbase/HBasePOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hbase/HBasePOJOPutOperator.java
- contrib/src/main/java/com/datatorrent/contrib/util/FieldValueGenerator.java
- contrib/src/test/java/com/datatorrent/contrib/hbase/HBasePOJOInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/hbase/HBasePOJOPutOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/hbase/HBaseUtil.java
- contrib/src/test/java/com/datatorrent/contrib/util/POJOTupleGenerateOperator.java
- contrib/src/test/java/com/datatorrent/contrib/util/TestPOJO.java
- contrib/src/test/java/com/datatorrent/contrib/util/TupleCacheOutputOperator.java
- contrib/src/test/java/com/datatorrent/contrib/util/TupleGenerateCacheOperator.java
- contrib/src/test/java/com/datatorrent/contrib/util/TupleGenerator.java
- library/src/main/java/com/datatorrent/lib/util/FieldInfo.java
- library/src/main/java/com/datatorrent/lib/util/FieldValueGenerator.java
- library/src/main/java/com/datatorrent/lib/util/TableInfo.java
I didn't create a specific pull branch as it only includes one commitment.
> MLHR-1731: implement hbase input operator

- library/src/main/java/com/datatorrent/lib/algo/Sampler.java
- library/src/test/java/com/datatorrent/lib/algo/SamplerTest.java
Himanshu requested this during the category and property cleanup of Malhar for app builder.
> Made Sampler operator simpler to use.

- contrib/src/main/java/com/datatorrent/contrib/aerospike/AerospikePOJONonTransactionalPutOperator.java
- contrib/src/main/java/com/datatorrent/contrib/aerospike/AerospikePOJOTransactionalPutOperator.java
- contrib/src/main/java/com/datatorrent/contrib/cassandra/CassandraPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/cassandra/CassandraPOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchbase/CouchBasePOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchbase/CouchbasePOJOSetOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/CouchDBPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/couchdb/CouchDBPOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hbase/HBasePOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/hbase/HBasePOJOPutOperator.java
- contrib/src/main/java/com/datatorrent/contrib/memcache/MemcachePOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/memsql/MemsqlPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/memsql/MemsqlPOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/mongodb/MongoDBPOJOOutputOperator.java
- library/src/main/java/com/datatorrent/lib/appdata/snapshot/AppDataSnapshotServerPOJO.java
- library/src/main/java/com/datatorrent/lib/db/jdbc/JdbcPOJOOutputOperator.java
> Mark POJO enabled operators @Evolving

- library/src/main/java/com/datatorrent/lib/db/jdbc/AbstractJdbcInputOperator.java
> statement should be transient

- contrib/src/main/java/com/datatorrent/contrib/r/RMax.java
- contrib/src/main/java/com/datatorrent/contrib/r/RMin.java
- contrib/src/main/java/com/datatorrent/contrib/r/RScript.java
- contrib/src/main/java/com/datatorrent/contrib/r/RStandardDeviation.java
> MLHR-1740:Fix names and description of properties in R operator

- demos/twitter/src/main/resources/META-INF/properties.xml
> Reduced sliding window count for TwitterDemo.

- benchmark/src/main/java/com/datatorrent/benchmark/algo/UniqueValueCountBenchmarkApplication.java
- benchmark/src/main/java/com/datatorrent/benchmark/script/RubyOperatorBenchmarkApplication.java
- benchmark/src/test/java/com/datatorrent/benchmark/memsql/MemsqlInputBenchmarkTest.java
- benchmark/src/test/java/com/datatorrent/benchmark/memsql/MemsqlOutputBenchmark.java
> Fixed compilation errors in benchmark application.

- contrib/pom.xml
- contrib/src/main/java/com/datatorrent/contrib/redis/AbstractRedisInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/redis/RedisKeyValueInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/redis/RedisMapAsValueInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/redis/RedisPOJOInputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/redis/RedisPOJOOutputOperator.java
- contrib/src/main/java/com/datatorrent/contrib/redis/RedisStore.java
- contrib/src/test/java/com/datatorrent/contrib/redis/RedisInputOperatorTest.java
- contrib/src/test/java/com/datatorrent/contrib/redis/RedisPOJOOperatorTest.java
- demos/machinedata/pom.xml
.. and corresponding unit tests
> MLHR-1748 #resolve #comment Created concrete input and output operators for Redis Store
